packages:
  - 'rspack/**'
  - 'rsbuild/**'
  - 'rslib/**'
  - 'rspress/**'
  - 'rsdoctor/**'
  - 'rstest/**'
  - '!**/dist'

dedupePeers: true

overrides:
  '@swc/plugin-prefresh': 13.0.0
  '@swc/plugin-styled-components': 13.0.0
